name: Deploy Laravel Project

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        run: |
          alias composer="php composer.phar" |
          php composer install --no-dev --optimize-autoloader

      - name: Deploy to Server
          run: |
            ssh ssh -o StrictHostKeyChecking=no ${{ secrets.HOST_USER }}@$${{ secrets.HOST_IP }} 'cd /www/portfolio/back && git pull origin main && php artisan migrate --force && php artisan config:cache && php artisan route:cache'
          env:
            HOST_USER: ${{ secrets.HOST_USER }}
            HOST_IP: ${{ secrets.HOST_IP }}
            HOST_SSH_KEY: ${{ secrets.HOST_SSH_KEY }}
