name: Deploy Laravel Project

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.HOST_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.HOST_USER }}@${{ secrets.HOST_IP }} << 'EOF'
            cd ~/www/portfolio/back

            echo "→ Pulling latest changes..."
            git pull origin master

            echo "→ Installing dependencies..."
            /home/manuleyva/.bin/php ~/composer.phar install --no-dev --optimize-autoloader

            echo "→ Clearing caches..."
            /home/manuleyva/.bin/php artisan cache:clear
            /home/manuleyva/.bin/php artisan config:clear
            /home/manuleyva/.bin/php artisan route:clear
            /home/manuleyva/.bin/php artisan view:clear

            echo "→ Running migrations..."
            /home/manuleyva/.bin/php artisan migrate --force

            echo "→ Caching config and routes..."
            /home/manuleyva/.bin/php artisan config:cache
            /home/manuleyva/.bin/php artisan route:cache
            /home/manuleyva/.bin/php artisan view:cache

            echo "→ Optimising filament..."
            /home/manuleyva/.bin/php artisan filament:optimize

            echo "✅ Deployment complete!"
          EOF
        env:
          HOST_IP: ${{ secrets.HOST_IP }}
          HOST_USER: ${{ secrets.HOST_USER }}
